---
title: "Pollinator Flexibility Shapes Plant-pollinator Interactions in Willamette Valley Prairies"
author: "Jacob Swanson"
date: "2025-11-11"
output: html_document
bibliography: Bibliography.bib
---

## Literature review (~5 paragraphs)

### Paragraph 1 — Problem & significance (big‑picture reviews)

Mutualisms—interactions where species provide reciprocal benefits—are central to biodiversity and ecosystem function. Plant-pollinator networks are among some of the most widespread and consequential mutualisms influencing species fitness, population dynamics, and even the trajectory of evolution [@bronstein2015mutualism]. Yet mutualistic outcomes are not fixed: the benefits one species receives often depend on the broader community context, where indirect interactions can tip the balance between facilitation and competition [@darwin1959origin; @wootton1994nature; @cosmo2023indirect]. Predicting when mutualisms maintain diversity versus antagonisms that impose costs remains a central challenge in ecology and evolution. 

### Paragraph 2–3 — Past work & data landscape (who/where/how; gaps)

Previous studies have demonstrated how plants compete via pollinator sharing, and the consequences for plant reproduction. For example, @bergamo_pollinator-mediated_2021 examined the fitness consequences of pollinator-mediated indirect interactions in plant-pollinator networks using seed set data for 23 different focal species. They found that plant fecundity was influenced by how pollinators are shared, where more generalized plants monopolized pollinator visitation likely harming co-flowering specialist plants reproduction. @arceo-gomez_plantpollinator_2020 explores how network properties that are related to plant-pollinator visitation, such as network position and role are related to patterns of pollen deposition. By mapping plant-pollinator networks in early succession grasslands in Tennessee and collecting style data for focal species, they quantified conspecific and heterospecific load size. They found that network metrics may predict pollen deposition--such that the degree of plant specialization may be associated with increased heterospecific load size. Similarly, @wei_pollinators_2021 examined how niche partitioning and asymmetric facilitation maintain rare species persistence. They collected plant-pollinator interaction data over two flowering seasons in serpentine seep communities and taxonomically identified 3.1 million pollen grains from flower stigmas. They found in species-rich communities, plant-pollinator interactions favor rare species through asymmetric facilitation--where generalists plants, though they received higher visitation, suffered fitness consequences due to conspecific pollen loss. Interestingly, these studies used different metrics to assess plant fitness (pollen vs seed set), which produced contrasting outcomes. Additionally, these studies do not consider how pollinator sharing may be variable across communities, where some communities may have high vs. low pollination niche overlap, leaving a paucity of information that may inform which network architecture is mutualistic vs. antagonistic. 

Notably, pollinator interactions are flexible changing behavior through space and time which likely challenges our ability to generalize niche breadth across plant species. At the population level, pollinators can change their interaction partners in the event of a disturbance (e.g., wildfire) [@ponisio2020pyrodiversity], and with resource availability through niche partitioning [@gaiarsa2021pollinator; @valdovinos_niche_2016]. As pollinators change their interaction partners, plant niche breadth becomes stochastic and context dependent. For example, @herrera_plant_2005 examined whether \textit{L. latifolia} populations and individuals differ in their degree of pollinator generalization by conducting a multi-year census of plant-pollinator interactions across southeastern Spain. Using rarefaction analyses they compared individual and population-level generalization, and found that plant generalization is not a fixed species-level trait, and variation in generalization was observed across populations of \textit{L. latifolia}. Similarly, @gonzalez2015floral conducted a study that characterized pollinator assemblages across two years for six different populations of \textit{A. ligtu simsii} in the same region in the Mediterranean. They found that \textit{A. ligtu simsii} populations among years varied in pollinator abundance, richness, and diversity. While these studies offer valuable insights, we still lack a clear understanding of how pollinator flexibility affects plant niche breadth. Without this knowledge, we are limited in our ability to draw robust conclusions on how variation in pollination niche overlap affects the reproduction of plants with differing niche breadths.

### Paragraph 4 — Purpose & why now

Over the past 175 years native prairie and savanna ecosystems in the Pacific Northwest have suffered a drastic decline, with approximately 90-98% lost throughout the region [@sinclair2006bunchgrass; @altman2011historical]. A novel conservation strategy with high potential to support restoration of these imperiled habitats and secure vital ecosystem services, is using seed mixes that focus on species combinations that maximize pollinator efficiency for rare or restoration-priority plants.  Mutualistic network theory predicts that the effects one plant has on another via pollinator sharing depends on both niche overlap and breadth. Yet, the composition of plant-pollinator interactions is highly dynamic, even well-characterized pairwise outcomes differ across space, time, and disturbance gradients [@aarssen1989competitive; @aarssen1992causes; @bengtsson1994competition; @endres2021plant]. Thus, empirical tests that link network context with reproductive outcomes are important. Without such integration, we cannot predict which network architecture initiates a mutualistic vs. antagonistic plant-pollinator network. Here, I examine whether pollinator flexibility and network niches influence variability in plant niche breadth. The findings will help determine if variability in plant niche breadth is structured by pollinator flexibility, or simply a product of chance. Additionally, by demonstrating whether plant niche breadth varies with pollinator partner flexibility, this important step will inform my thesis work, in which I plan to test how pollination niche overlap affects the reproduction of plants that differ in niche breadth.

### Paragraph 5 — Hypotheses (directional) & brief rationale
- H1: I predict that generalist plants will have more variable pollinator partners than would be expected if I sample from the regional species pool. 

- H2: I predict that specialist plants will have less variable pollinator partners than would be expected if I sample from the regional species pool. 

- H3: I predict interaction \beta-diversity will explain plant niche breadth (d) with a positive relationship.

Rationale: Pollinators flexibility is likely influenced by many plant functional traits. More specialized plants often possess traits that require co-evolved pollinator interactions, resulting in more specialized interactions and a narrow niche breadth. In contrast, more generalized plants typically have traits that are suitable for a wide range of pollinators, which may explain why central generalists often exhibit more variable niche breadth. Additionally, \beta-diversity—a measure used to quantify a pollinator’s ability to switch floral interaction partners—may help explain plant niche breadth, since changes in pollinator behavior alter the composition of pollinators visiting a given plant.

## Dataset identification
- Willamete Data (URL/DOI): 
Collector: Susan Waters and colleagues
Methods: Timed plant-pollinator surveys at several sites in multiple years across the Willamette Valley
Columns: site_abbrev	site	date	iteration	time	observer	temp	hum	wind	plant_codon	plants_per_m2	patch_size	field notes	Multiplier	specimen_ID	Voucher Present	Project	insect_order	Misc Group	insect_family	insect_subfamily	insect_tribe	insect_genus	insect_subgenus	insect_species	insect_spp	Sex	lab notes	det_by	box	transect	Country	State	County	Latitude	Longitude	Elevation	tblPlants.Order	tblPlants.Family	tblPlants.Genus	tblPlants.Species	NonPlantDescription

- Raw Data → Adjacency network → Richness matrix → AB test → Visualization

## Workflow plan (prose)
1) Cleaning & validation: Normalize raw floral data using GBIF (validation). Change date to single format, class type date, validate with class function, create year column. Drop empty cells and NA from Genus, Species, and PlantGenusSpecies columns. Create GenusSpecies column (for pollinators). Sum NAs in each of these columns to validate (should be 0). Create interactions column (plant-pollinator). Drop non-bees by subsetting data, validate with unique function.
2) Aggregations/derivations: see functions/loops. 
3) Functions/loops (inputs → outputs):
I will create a function to prepare data to analyze site-level species interaction patterns in \beta-diversity, focusing on specific year, and aggregating species interactions across sites and dates.  This function will subset data by year, aggregate interactions, create a list of data frames for each focal species, filter by observation thresholds (3), create empty matrices for each site with unique interacting species, populate matrices with observed abundances and then return the results. 
I will create a function that iterates over a list of networks by computing species-level metrics (degree, centrality, etc)
4) Statistical test + programmatic implementation: I will generate a null model that standardizes for partner \beta-diversity scores by standardizing for partner \alpha diversity to test whether observed patterns are different from what would occur by chance. Linear model testing whether network metrics (\beta-diversity and network niches) predict plant specialization (d). 
5) Planned visualizations/tables: Linear regression model with \beta-diversity and other network niches regressed against plant specialization (d). 
6) Risks & mitigations: subset data to only account for bees, as they are the primary pollinators in this system. See mitigations and risk management discussed in workflow #1. 

